config/routes.rb
RailsSched::Application.routes.draw do
resources :schedules do
    collection { post :import }
  end
 
  root to: "schedules#index"

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
   require 'CSV'
   
   validates_datetime :start_time, :after => :now, :message => "Start Time must be in the future"
   validates_datetime :end_time, :after => :now, :message => "End Time must be in the future"
   validates :start_time, :end_time, :overlap => {:scope => "first_name"}, :overlap => {:scope => "last_name"}
   
    def self.import(file)
      CSV.foreach(file.path, headers: true) do |row|
   
        schedule_hash = row.to_hash # exclude the price field
        schedule = Schedule.where(id: schedule_hash["id"])
   
        if schedule.count == 1
          schedule.first.update_attributes(schedule_hash)
        else
          Schedule.create!(schedule_hash)
        end # end if !product.nil?
      end # end CSV.foreach
    end # end self.import(file)
  end # end class

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
    @schedule = Schedule.new
    respond_to do |format|
      format.html
    end
  end
  
  def import
    Schedule.import(params[:file])
    redirect_to root_url, notice: "Schedules imported."
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render action: 'show', status: :created, location: @schedule }
      else
        format.html { render action: 'new' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:start_time, :end_time, :first_name, :last_name, :comments)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsSched</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/schedules/_form.html.erb
<%= form_for(@schedule, html: {class: 'form-horizontal', multipart: true } ) do |f| %>

<% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this edit from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="center">
	  <div class="field">
	    <%= f.label :first_name %><br>
	    <%= f.text_field :first_name %>
	  </div>
	  <div class="field">
	    <%= f.label :last_name %><br>
	    <%= f.text_field :last_name %>
	  </div>
	  <div class="field">
	    <%= f.label :comments %><br>
	    <%= f.text_field :comments %>
	  </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<div class="header-container">
<h2> Welcome to @Acme Scheduling System</h2>
</div>
<br />
<hr>

<h3> Step1 - Import a CSV File (When a new schedule comes)</h3>
  <%= form_tag import_schedules_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>
<br />
<br />
<hr>

<h3>Schedule a Time</h3>
<p> <b>Time must be after today and must not overlap with an existing time in the scheduling system </b></p>

<%= render "schedules/form" %>

<br />
<br />
<hr>

<h2> List of Times </h2>
<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Comments</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.start_time.strftime('%m/%d/%Y %l:%M %P') %></td>
        <td><%= schedule.end_time.strftime('%m/%d/%Y %l:%M %P') %></td>
        <td><%= schedule.first_name %></td>
        <td><%= schedule.last_name %></td>
        <td><%= schedule.comments %></td>
        <td><%= button_to "Edit Time", edit_schedule_path(schedule), :method => "get" %></td>
        <td><%= button_to "Delete Time", schedule, :method=>:delete, :class=>:destroy %></td>
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @schedule.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @schedule.end_time %>
</p>

<p>
  <strong>First name:</strong>
  <%= @schedule.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @schedule.last_name %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @schedule.comments %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>